### ISSUE TITLE
Operator unable to initialize

### ISSUE THREAD

**Issue by ankitdh7** [coralogix/coralogix-operator#173]
**Problem**

The latest version of coralogix-operator is unable to start.

**Error:**
```
goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.init.func1({0x2ef5430?, 0x1be8300?}, {0x1ec6360, 0xc000129440})
	/go/pkg/mod/google.golang.org/protobuf@v1.34.2/reflect/protoregistry/registry.go:56 +0x1ec
google.golang.org/protobuf/reflect/protoregistry.(*Types).RegisterExtension(0xc00012cd50, {0x1ef02a0, 0x2f0a580})
	/go/pkg/mod/google.golang.org/protobuf@v1.34.2/reflect/protoregistry/registry.go:554 +0x5b2
google.golang.org/protobuf/internal/filetype.Builder.Build({{{0x1934488, 0x57}, {0x2e14b80, 0x15f, 0x15f}, 0x0, 0x1, 0x1, 0x0, {0x0, ...}, ...}, ...})
	/go/pkg/mod/google.golang.org/protobuf@v1.34.2/internal/filetype/build.go:236 +0x627
github.com/coralogix/coralogix-management-sdk/go/internal/coralogixapis/logs2metrics/v2.file_com_coralogixapis_logs2metrics_v2_audit_log_proto_init()
	/go/pkg/mod/github.com/coralogix/coralogix-management-sdk@v0.2.2-0.20241010083215-2b986bff8a4e/go/internal/coralogixapis/logs2metrics/v2/audit_log.pb.go:178 +0x1f8
github.com/coralogix/coralogix-management-sdk/go/internal/coralogixapis/logs2metrics/v2.init.0()
	/go/pkg/mod/github.com/coralogix/coralogix-management-sdk@v0.2.2-0.20241010083215-2b986bff8a4e/go/internal/coralogixapis/logs2metrics/v2/audit_log.pb.go:144 +0xf
panic: proto: extension number 5000 is already registered on message google.protobuf.MethodOptions
	previously from: "github.com/coralogix/coralogix-management-sdk/go/internal/coralogixapis/apm/common/v2"
	currently from:  "github.com/coralogix/coralogix-management-sdk/go/internal/coralogixapis/logs2metrics/v2"
See https://protobuf.dev/reference/go/faq#namespace-conflict


goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.init.func1({0x2ef5430?, 0x1be8300?}, {0x1ec6360, 0xc000067480})
	/go/pkg/mod/google.golang.org/protobuf@v1.34.2/reflect/protoregistry/registry.go:56 +0x1ec
google.golang.org/protobuf/reflect/protoregistry.(*Types).RegisterExtension(0xc0000c0d50, {0x1ef02a0, 0x2f0a580})
	/go/pkg/mod/google.golang.org/protobuf@v1.34.2/reflect/protoregistry/registry.go:554 +0x5b2
google.golang.org/protobuf/internal/filetype.Builder.Build({{{0x1934488, 0x57}, {0x2e14b80, 0x15f, 0x15f}, 0x0, 0x1, 0x1, 0x0, {0x0, ...}, ...}, ...})
	/go/pkg/mod/google.golang.org/protobuf@v1.34.2/internal/filetype/build.go:236 +0x627
github.com/coralogix/coralogix-management-sdk/go/internal/coralogixapis/logs2metrics/v2.file_com_coralogixapis_logs2metrics_v2_audit_log_proto_init()
	/go/pkg/mod/github.com/coralogix/coralogix-management-sdk@v0.2.2-0.20241010083215-2b986bff8a4e/go/internal/coralogixapis/logs2metrics/v2/audit_log.pb.go:178 +0x1f8
github.com/coralogix/coralogix-management-sdk/go/internal/coralogixapis/logs2metrics/v2.init.0()
	/go/pkg/mod/github.com/coralogix/coralogix-management-sdk@v0.2.2-0.20241010083215-2b986bff8a4e/go/internal/coralogixapis/logs2metrics/v2/audit_log.pb.go:144 +0xf
panic: proto: extension number 5000 is already registered on message google.protobuf.MethodOptions
	previously from: "github.com/coralogix/coralogix-management-sdk/go/internal/coralogixapis/apm/common/v2"
	currently from:  "github.com/coralogix/coralogix-management-sdk/go/internal/coralogixapis/logs2metrics/v2"
See https://protobuf.dev/reference/go/faq#namespace-conflict


goroutine 1 [running]:

```

**Steps to reproduce**

- Clone the [repo](https://github.com/coralogix/coralogix-operator)
- Go to directory
```
cd coralogix-operator
```
- Install the coralogix-operator
```
helm install coralogix-operator charts/coralogix-operator --set secret.data.apiKey="<coralogix_key>" --set coralogixOperator.image.tag="0.2.2" --set coralogixOperator.region="<coralogix_region>"
```
**Expected Outcome**
The coralogix operator should be running fine

**Actual Outcome**
The coralogix operator stuck in the crashloop.
![image](https://github.com/user-attachments/assets/acaaa2be-d5c4-40f2-bd4d-3dbb9f3cd807)
![image](https://github.com/user-attachments/assets/ba8dfdef-7a2e-418a-9cd5-6c3d113f5ba3)

**Comment by assafad1** [comment]
@ankitdh7 Thanks for reporting this issue! It was fixed by https://github.com/coralogix/coralogix-operator/pull/175.
